#!/usr/bin/perl
use strict;
use warnings;
use Path::Tiny;

my $testhead = <<EOF;
// This file is generated by gentests.pl
// Modifying it is pointless; modify gentests.pl
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "codelist.h"

#define ARRAYSIZE(array, type) ((sizeof (array)) / (sizeof(type)))

size_t code_list_vec(struct code_list_node* node_vec[],
                     struct code_list* code_list) {
    struct code_list_node * nv = calloc(code_list->size, sizeof *nv);
    struct code_list_node* node = code_list->first;

    for (size_t i = 0; node != NULL; node = node->next) {
        nv[i] = *node;
        nv[i++].next = NULL;
    }

    *node_vec = nv;
    return code_list->size;
}

const char* op_to_str[] = {
    "OP_INVALID",
    "OP_ASCII_ADD",
    "OP_ASCII_SUB",
    "OP_CELL_ADD",
    "OP_CELL_SUB",
    "OP_OUT",
    "OP_IN",
    "OP_LOOP_LABEL",
    "OP_LOOP_JUMP"
};

void print_code_list_vec(FILE* fp, struct code_list_node vec[], size_t size) {
    if (size == 0) {
        fprintf(fp, "{}");
        return;
    }

    fprintf(fp, "{{%s, %u}", op_to_str[vec[0].id], vec[0].arg);
    for (size_t i = 1; i < size; ++i) {
        fprintf(fp, ", {%s, %u}", op_to_str[vec[i].id], vec[i].arg);
    }
    fprintf(fp, "}");
}

struct tt_t {
    struct {
    const char *    str;
    size_t          size;
    } in;
    struct {
        struct code_list_node   vec[BUFSIZ];
        size_t                  size;
    } out;
} tt[] = {
EOF

my $testfoot = <<EOF;
int main() {
    int errs = 0;
    for (size_t i = 0; i < ARRAYSIZE(tt, struct tt_t); ++i) {
        struct code_list* clist = make_code_list(tt[i].in.str, tt[i].in.size);

        if (clist == NULL) {
            printf("make_code_list(\\"%s\\", %lu) == NULL; wanted not NULL\\n",
                   tt[i].in.str, tt[i].in.size);
            ++errs;
            continue;
        }

        struct code_list_node* clvec = NULL;
        size_t clvec_size = code_list_vec(&clvec, clist);
        free_code_list(clist);

        if (clvec_size != tt[i].out.size) {
            printf("make_code_list(\\"%s\\", %lu)->size == %lu; wanted %lu\\n",
                   tt[i].in.str, tt[i].in.size, clvec_size, tt[i].out.size);
        } else if (memcmp(clvec, tt[i].out.vec, clvec_size)) {
            printf("make_code_list(\\"%s\\", %lu) == ", tt[i].in.str,
                   tt[i].in.size);
            print_code_list_vec(stdout, clvec, clvec_size);
            printf("; wanted ");
            print_code_list_vec(stdout, tt[i].out.vec, tt[i].out.size);
        } else {
            continue;
        }
        ++errs;
    }

    return errs;
}
EOF

sub print_code_vec_node {
    my ($fh, $str, $prefix) = @_;
    my $len = length $str;

    if ($str =~ m/>+/) {
        print $fh $prefix, "{OP_CELL_ADD, $len, NULL}";
    } elsif ($str =~ m/<+/) {
        print $fh $prefix, "{OP_CELL_SUB, $len, NULL}";
    } elsif ($str =~ m/\++/) {
        print $fh $prefix, "{OP_ASCII_ADD, $len, NULL}";
    } elsif ($str =~ m/\-+/) {
        print $fh $prefix, "{OP_ASCII_SUB, $len, NULL}";
    } elsif ($str =~ m/,+/) {
        print $fh $prefix, "{OP_IN, 1, NULL}";
    } elsif ($str =~ m/\.+/) {
        print $fh $prefix, "{OP_OUT, 1, NULL}";
    } elsif ($str =~ m/\[+/) {
        print $fh $prefix, "{OP_LOOP_LABEL, 1, NULL}";
    } elsif ($str =~ m/\]+/) {
        print $fh $prefix, "{OP_LOOP_JUMP, 1, NULL}";
    }
}

sub print_tt {
    my ($fh, $sample) = @_;

    my $len = length $sample;
    my $cstr = $sample;
    $cstr =~ s/\n/\\n/g;
    $cstr =~ s/"/\\"/g;

    print $fh
        "\t{\n",
        "\t\t{\n",
        "\t\t\t\"$cstr\",\n",
        "\t\t\t$len\n",
        "\t\t},\n",
        "\t\t{\n",
        "\t\t\t{\n";
   
    my $stripped = $sample;
    $stripped =~ tr/[\+\-><\.,\[\]]//cd;
    my @matches = $stripped =~ m/>+|<+|\++|\-+|,|\.|\[|\]/g;
    my $nodesn = scalar @matches;
    my $last_match = pop @matches;

    my $cvec_node = "";
    foreach (@matches) {
        print_code_vec_node($fh, $_, "\t\t\t\t");
        print $fh ",\n";
    }

    print_code_vec_node($fh, $last_match, "\t\t\t\t");
    print $fh
        "\n",
        "\t\t\t},\n",
        "\t\t\t$nodesn\n",
        "\t\t}\n",
        "\t}";
}

sub print_fail_node {
    my ($fh, $fail) = @_;

    my $len = length $fail;
    my $cstr = $fail;
    $cstr =~ s/\n/\\n/g;
    $cstr =~ s/"/\\"/g;

    print $fh "\t{\n\t\t\"$cstr\",\n\t\t$len\n\t}";
}

open(UNITTESTS, ">unittests.c") or die "couldn't open file unittests.c, $!";
print UNITTESTS $testhead;

my @samples_files = glob("samples/*.0.b");
my @samples;
foreach (@samples_files) {
    my $src = path($_)->slurp() or die "couldn't open file $_, $!";
    push @samples, $src;
}
my $last_sample = pop @samples;

foreach (@samples) {
    print_tt(\*UNITTESTS, $_);
    print UNITTESTS ",\n";
}

print_tt(\*UNITTESTS, $last_sample);
print UNITTESTS "\n};\n\n";

my @fail_files = glob("samples/*.1.b");
my @fails;
foreach (@fail_files) {
    my $src = path($_)->slurp() or die "couldn't open file $_, $!";
    push @fails, $src;
}
my $last_fail = pop @fails;

print UNITTESTS
    "struct fail_t {\n",
    "\tconst char *\tstr;\n",
    "\tsize_t\t\t\tsize;\n",
    "} fails[] = {\n";

foreach (@fails) {
    print_fail_node(\*UNITTESTS, $_);
    print UNITTESTS ",\n";
}

print_fail_node(\*UNITTESTS, $last_fail);
print UNITTESTS "\n};\n\n";

print UNITTESTS "$testfoot";
